import { llmClient } from '../llm-client.js';

export interface TailorResponse {
  tailoredTex: string;
}

const TAILOR_SUBSTANCE_SYSTEM_PROMPT = `
You are a LaTeX expert and a professional career coach. Your task is to modify a LaTeX resume to perfectly align with a specific job description.

Step 1: Analyze the JD for key skills, responsibilities, and seniority.
Step 2: Modify the LaTeX content within the provided \`resumeTex\` to highlight the candidate's relevance.

Rules for modification:
- Reorder bullet points in experience sections to put the most relevant work first.
- Naturally incorporate keywords from the JD into the professional summary and work experience bullets.
- Do NOT fabricate experience. Only emphasize and rephrase existing points.
- Ensure the LaTeX syntax remains perfectly valid. Do NOT break command structures (e.g., \\item, \\section).
- Maintain the original document class and styling.

Your output MUST be the full LaTeX source code of the tailored resume.
`;

const HUMANIZE_SYSTEM_PROMPT = `
You are a master of natural language. You have been given a resume that has been automatically tailored for a job.
Your task is to refine the writing to sound more human, less repetitive, and less like it was generated by an AI.

- Remove overly formal or "AI-sounding" buzzwords (e.g., "leveraged", "synergy", "orchestrated" - unless they fit the context perfectly).
- Vary sentence length and structure.
- Ensure a professional but conversational tone that matches the candidate's original voice.
- Ensure the LaTeX syntax remains intact.

Your output MUST be the final refined LaTeX source code.
`;

export const tailorResume = async (jd: string, resumeTex: string): Promise<string> => {
  console.log('[tailor-resume] Starting Pass 1 (Substance)...');
  
  // Pass 1: Substance Tailoring
  const pass1Response = await llmClient.complete({
    messages: [
      { role: 'system', content: TAILOR_SUBSTANCE_SYSTEM_PROMPT },
      { role: 'user', content: `Job Description:\n"""\n${jd}\n"""\n\nOriginal LaTeX Resume:\n"""\n${resumeTex}\n"""` }
    ],
    temperature: 0.2,
    maxTokens: 4096, // Resumes are long
  });

  const tailoredSubstance = pass1Response.content;
  console.log('[tailor-resume] Pass 1 complete. Starting Pass 2 (Humanization)...');

  // Pass 2: Humanization
  const pass2Response = await llmClient.complete({
    messages: [
      { role: 'system', content: HUMANIZE_SYSTEM_PROMPT },
      { role: 'user', content: `Tailored LaTeX Resume:\n"""\n${tailoredSubstance}\n"""` }
    ],
    temperature: 0.4, // Higher temperature for more natural language
    maxTokens: 4096,
  });

  console.log('[tailor-resume] Pass 2 complete.');
  return pass2Response.content;
};
